// <auto-generated />
using System;
using KBank_Web_API.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KBank_Web_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007183128_fixBugsModelsMigrationsFive")]
    partial class fixBugsModelsMigrationsFive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KBank_Web_API.Models.CompraParcelada", b =>
                {
                    b.Property<int>("CompraParceladaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompraParceladaId"));

                    b.Property<string>("CategoriaCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantidadeParcelada")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TipoCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("ValorParcela")
                        .IsRequired()
                        .HasColumnType("double");

                    b.HasKey("CompraParceladaId");

                    b.ToTable("ComprasParceladas");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Parcela", b =>
                {
                    b.Property<int>("ParcelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParcelaId"));

                    b.Property<int>("CompraParceladaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataParcela")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<double?>("ValorParcela")
                        .HasColumnType("double");

                    b.HasKey("ParcelaId");

                    b.HasIndex("CompraParceladaId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransacaoId"));

                    b.Property<string>("CategoriaTransacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParcelaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("ValorTransacao")
                        .HasColumnType("double");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<double>("SaldoAtual")
                        .HasColumnType("double");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Parcela", b =>
                {
                    b.HasOne("KBank_Web_API.Models.CompraParcelada", "compraParcelada")
                        .WithMany("Parcelas")
                        .HasForeignKey("CompraParceladaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compraParcelada");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Transacao", b =>
                {
                    b.HasOne("KBank_Web_API.Models.Parcela", "Parcela")
                        .WithMany()
                        .HasForeignKey("ParcelaId");

                    b.HasOne("KBank_Web_API.Models.Usuario", "usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Parcela");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("KBank_Web_API.Models.CompraParcelada", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("KBank_Web_API.Models.Usuario", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
